SG-1503 - Drupal 9
SFDigitalServices/sfgov pull request #1059
Opened 2021-10-22 08:34 UTC by aekong

Upgrade to Drupal 9

2021-11-01 19:38 UTC, arlina-espinoza requested changes
Hi @aekong! This is looking good. I added some feedback. Thanks!

2021-11-01 19:38 UTC, arlina-espinoza commented on web/modules/custom/sfgov_departments/sfgov_departments.module
> +          MessengerInterface::addMessage(t('"@parent_department" is a parent department of "@department" and has been added by default. You can remove this selection if it does not apply for this con
```suggestion
          \Drupal::messenger()->addMessage(t('"@parent_department" is a parent department of "@department" and has been added by default. You can remove this selection if it does not apply for this content.', [
```

2021-11-01 19:38 UTC, arlina-espinoza commented on web/modules/custom/sfgov_departments/src/SFgovDepartment.php
> +class SFgovDepartment {
@aekong This class (and possible others?) was deleted from the codebase when we moved away from the group module. You might need to rebase your branch, or at least the sfgov_departments module.

2021-11-01 19:38 UTC, arlina-espinoza commented on web/modules/custom/sfgov_locations/sfgov_locations.module
> +    MessengerInterface::addMessage('We don’t have a main address for this department, so the department name, but no address will show.', 'warning');
```suggestion
    \Drupal::messenger()->addMessage('We don’t have a main address for this department, so the department name, but no address will show.', 'warning');
```

2021-11-01 19:38 UTC, arlina-espinoza commented on web/themes/custom/sfgovpl/sfgovpl.breakpoints.yml
> -sfgovpl.layout.small:
Does this file need to be deleted?

2021-11-01 22:03 UTC, aekong commented on web/modules/custom/sfgov_locations/sfgov_locations.module
> +    MessengerInterface::addMessage('We don’t have a main address for this department, so the department name, but no address will show.', 'warning');
updated, thanks!

2021-11-01 22:04 UTC, aekong commented on web/modules/custom/sfgov_departments/sfgov_departments.module
> +          MessengerInterface::addMessage(t('"@parent_department" is a parent department of "@department" and has been added by default. You can remove this selection if it does not apply for this con
updated, thanks!

2021-11-03 16:56 UTC, aekong commented on web/modules/custom/sfgov_departments/src/SFgovDepartment.php
> +class SFgovDepartment {
done (i hope 😬 )!

2021-11-03 16:56 UTC, aekong commented on web/themes/custom/sfgovpl/sfgovpl.breakpoints.yml
> -sfgovpl.layout.small:
done, thanks!

2021-11-04 22:44 UTC, arlina-espinoza approved these changes
LGTM! Awesome :)

2021-11-10 16:45 UTC, arlina-espinoza approved these changes
LGTM! Thanks!

2021-11-10 16:49 UTC, merged