[SG-1246] Implement view for unpublished content.
SFDigitalServices/sfgov pull request #702
Opened 2020-10-20 11:02 UTC by minnur

2020-10-21 07:01 UTC, arlina-espinoza requested changes

2020-10-21 07:01 UTC, arlina-espinoza commented on web/themes/custom/sfgovpl/templates/layout/page--403.html.twig
> +      <p>If you are a content publisher, log in to access this page.</p>
I think we should run the text through translations, as the 403 might come from a non-english page.

2020-10-21 07:17 UTC, minnur commented on web/themes/custom/sfgovpl/templates/layout/page--403.html.twig
> +      <p>If you are a content publisher, log in to access this page.</p>
Yep just added that.

2020-10-28 02:43 UTC, aekong approved these changes

2020-10-28 02:44 UTC, aekong approved these changes

2020-10-28 02:45 UTC, aekong approved these changes

2020-10-28 02:47 UTC, aekong approved these changes

2020-10-28 02:47 UTC, merged