[sg-1241] Don't machine-translate service cards when there is a human…
SFDigitalServices/sfgov pull request #787
Opened 2021-01-20 15:04 UTC by zakiya

… translation.

2021-01-20 15:08 UTC, zakiya commented
@arlina-espinoza Can I get a gut check on this approach? - I'm swapping variables when there's a translation of a referenced entity. Right now this is limited just to the transaction content type but i think I could apply this more generally with changes to the corresponding twig templates.

2021-01-21 20:26 UTC, arlina-espinoza requested changes

2021-01-22 16:35 UTC, zakiya commented on web/themes/custom/sfgovpl/includes/node.inc
> +  if (isset($_COOKIE['googtrans'])) {
Ah thanks. I had originally assumed the Drupal language was being overridden by the javascript client side. Code updated.

2021-02-12 18:36 UTC, aekong approved these changes

2021-02-12 21:01 UTC, aekong commented
changes resolved, but github thinks they're not.  merging with admin privileges

2021-02-12 21:01 UTC, merged