[SG-1298] Create proof of concept for HTML reports.
SFDigitalServices/sfgov pull request #840
Opened 2021-02-24 09:38 UTC by minnur

2021-07-26 15:33 UTC, zakiya requested changes
Some minor config things to clean up. Sooooo close.

2021-07-26 15:33 UTC, zakiya commented on composer-manifest.yaml
>      drupal/gtranslate: 1.13.0
Can you downgrade the group module to match develop? 1.4.0 breaks things. In [my PR](https://github.com/SFDigitalServices/sfgov/pull/945/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R70) I've got `"drupal/group": "1.3.0",` in composer.json. Hopefully it'll go into develop today.

2021-07-26 15:33 UTC, zakiya commented on composer.json
> +        "drupal/toc_api": "^1.0",
tmgmt_xtm was pulled from code. https://github.com/SFDigitalServices/sfgov/blob/develop/composer.json#L108 Keep. drupal/tmgmt.

2021-07-26 15:33 UTC, zakiya commented on config/core.extension.yml
> +  tmgmt_xtm: 0
tgmt_xtm should not be enabled.

2021-07-26 15:33 UTC, zakiya commented on config/filter.format.sf_basic_html.yml
> -      allowed_view_modes: {  }
I don't know anything about how SF.gov is using text formats. @aekong is this ok?

2021-07-26 15:33 UTC, zakiya commented on config/workflows.workflow.editorial.yml
>      - node.type.resource_collection
⭐

2021-07-26 15:33 UTC, zakiya commented on config/core.entity_form_display.node.report.default.yml
> +    type: boolean_checkbox
"Promoted to front page" should be hidden.

2021-07-26 15:33 UTC, zakiya commented on config/core.entity_form_display.node.report.default.yml
> +    type: boolean_checkbox
"Stick at top of lists" should be hidden.

2021-07-26 16:01 UTC, arshad commented on config/core.entity_form_display.node.report.default.yml
> +    type: boolean_checkbox
@zakiya it looks like this is now disabled in code? https://github.com/SFDigitalServices/sfgov/blob/develop/web/modules/custom/sfgov_admin/sfgov_admin.module#L336

I can't do it via the UI. It's disabled.

2021-07-26 16:40 UTC, zakiya commented on config/core.entity_form_display.node.report.default.yml
> +    type: boolean_checkbox
Can you try saving admin/structure/types/manage/report/display and `drush cex`? I think cause the config isn't updated you can still see these checkboxes under "Promotion Options" at https://pr-840-sfgov.pantheonsite.io/node/add/report Maybe you have to change something for it to pick it up. 

The code solution was mine but not thorough enough it seems. 

cc- @aekong @arlina-espinoza @bookworm2000

2021-07-26 16:52 UTC, arshad commented on composer.json
> +        "drupal/toc_api": "^1.0",
Thanks. Removed.

2021-07-26 16:54 UTC, arshad commented on composer-manifest.yaml
>      drupal/gtranslate: 1.13.0
Done.

2021-07-26 17:17 UTC, aekong commented on config/filter.format.sf_basic_html.yml
> -      allowed_view_modes: {  }
i'm trying to get into the pr env to see what this config does, but currently getting the "The website encountered an unexpected error. Please try again later." message.  This config is removing `media embed`?

2021-07-26 18:40 UTC, zakiya commented on config/filter.format.sf_basic_html.yml
> -      allowed_view_modes: {  }
Let's not spend anytime fixing the group module if we can help it.

2021-07-26 18:50 UTC, zakiya commented on config/filter.format.sf_basic_html.yml
> -      allowed_view_modes: {  }
Another suggestion I have is to pull database from live and rerun the the circle ci build. I think if the group 1.4.0 code was on this environment and the database was it updated it may be causing issues. I ran into this on 945.

2021-07-27 13:04 UTC, arshad commented on config/core.entity_form_display.node.report.default.yml
> +    type: boolean_checkbox
@zakiya Done. Thank you.

2021-07-27 13:05 UTC, arshad commented on config/filter.format.sf_basic_html.yml
> -      allowed_view_modes: {  }
@zakiya This worked. 🎉 Thank you.

2021-07-30 05:46 UTC, arshad commented on config/filter.format.sf_basic_html.yml
> -      allowed_view_modes: {  }
@zakiya Done. Reverted the changes to the format.

2021-07-30 13:54 UTC, zakiya approved these changes
We are a go. 🥳

2021-07-30 14:50 UTC, merged