WIP: SG-953
SFDigitalServices/sfgov pull request #957
Opened 2021-07-21 18:17 UTC by bookworm2000

Add department title in the news feed for each department.

Redirect the page from `news/dept_id` to `news/dept_name`.

2021-07-21 18:20 UTC, zakiya commented on web/modules/custom/sfgov_event_subscriber/sfgov_event_subscriber.module
> +}
Add new line at end of file.

2021-07-23 22:34 UTC, arlina-espinoza reviewed
Hi @bookworm2000 ,

I have a couple of ideas of how this could be implemented without handling the redirects in custom code.

One way it to do it is using _views_ on the news page display, by replacing the department ID contextual filter with a department title filter (and configuring it so it accepts it all lowercase and replacing spaces with dashes). If so, we'd also need to create an update function that creates a bulk of redirects from current paths to the new ones.

Another option would be to use path aliases. Create an alias for every department node with the correct aliased route. This would not break any existing paths and the way the site is setup, I believe it will always redirect to the aliased path if they exist.

Let me know your thoughts or if you want to chat.

2021-07-26 15:55 UTC, bookworm2000 commented
@arlina-espinoza Ah, I like the idea of using the aliases! I'll go in that direction today

2021-07-26 23:32 UTC, bookworm2000 commented
@arlina-espinoza This is working locally now. Code definitely looks better not including all that event subscriber stuff.

2021-07-29 01:46 UTC, bookworm2000 commented
@arlina-espinoza Not sure why this is rendering correctly for the `/news/160` page but not for the `/news/topics/794` page. Do you see anything obvious I am doing incorrectly?

2021-08-02 20:32 UTC, arlina-espinoza requested changes
Thanks @bookworm2000 ,

This is looking good, but we also need to add node create/edit/delete hooks to correspondingly sync up the news alias when a new node is created/edited, so that the work applies to future content.

As another improvement, the alias only applies to English - translating a page defaults to the node ID path (example: `/es/news/217`). I'd think we'd also need aliases for the other languages, but you'll need to test it out. :sweat_smile:

2021-08-02 20:32 UTC, arlina-espinoza commented on web/themes/custom/sfgovpl/includes/views.inc
> +
Wondering if this works for other languages other than English?

2021-08-02 20:32 UTC, arlina-espinoza commented on web/themes/custom/sfgovpl/templates/views/views-view--news--page-1.html.twig
> +  {% set banner_subtitle = field_topic %}
This should also be moved to the other PR for topics.

2021-08-03 01:35 UTC, bookworm2000 commented on web/themes/custom/sfgovpl/templates/views/views-view--news--page-1.html.twig
> +  {% set banner_subtitle = field_topic %}
removed from this PR

2021-08-03 01:35 UTC, bookworm2000 commented on web/themes/custom/sfgovpl/includes/views.inc
> +
Miraculously this does work, after testing on several languages.

2021-08-03 01:36 UTC, bookworm2000 commented on web/modules/custom/sfgov_departments/src/SFgovDepartment.php
> +    // Add redirects for news view pages.
@arlina-espinoza The delete works fine, but I'm not thrilled with the create and edit content. I don't know how to get this in better shape.

2021-08-09 19:26 UTC, arlina-espinoza requested changes
Thanks @bookworm2000 , I've added some comments. LMK if you want to discuss further. Thanks!

2021-08-09 19:26 UTC, arlina-espinoza commented on web/modules/custom/sfgov_departments/src/SFgovDepartment.php
> +            $path_alias->save();
I think we should edit the alias object to match the latest. And we should create a redirect from the old url to the new one (the Redirect module might already do this because of the setting `Automatically create redirects when URL aliases are changed.`?)

2021-08-09 19:26 UTC, arlina-espinoza commented on web/modules/custom/sfgov_departments/src/SFgovDepartment.php
> +    // Add redirects for news view pages.
@bookworm2000 Could you rebase this against the latest `develop`? I think this file was deleted as part of the work of removing the group module. If so, you can move this into a hook on another custom module.

2021-08-10 00:41 UTC, bookworm2000 commented on web/modules/custom/sfgov_departments/src/SFgovDepartment.php
> +    // Add redirects for news view pages.
Rebased against develop. Yup that file was nuked so cannot use it!

2021-08-10 00:42 UTC, bookworm2000 commented
@arlina-espinoza I spent a lot more time today refining this and have tested it against new/updated/deleted department and topic nodes. Hopefully this looks better!

2021-08-16 20:19 UTC, arlina-espinoza approved these changes
LGTM :)

2021-08-16 20:20 UTC, merged