[SG-1408] Add check for resource description field
SFDigitalServices/sfgov pull request #972
Opened 2021-08-04 21:21 UTC by bookworm2000

URL addresses and email addresses break the tiles, so check this value when a user adds to the form, and throw a form error if found.

2021-08-09 17:44 UTC, arlina-espinoza requested changes
Hi @bookworm2000 ,
I've added a couple of suggestions. Thanks!

2021-08-09 17:44 UTC, arlina-espinoza commented on web/modules/custom/sfgov_campaigns/sfgov_campaigns.module
> +              $regex = '/[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})/';
This might be too specific (what if the email ends in `.info`, for example). Validating emails is always a pain, but in this case, you just want to make sure that something that looks like an email isn't entered, so I think the following regex would work just find: `\S+@\S+`. I have not test it it, but let me know if it does work.

2021-08-09 17:44 UTC, arlina-espinoza commented on web/modules/custom/sfgov_campaigns/sfgov_campaigns.module
> +              }
Let's split this up. 
```suggestion
              if ($has_http || $has_https) {
                $error_message = t('The campaign resource Resource Description field cannot contain a web address.');
                $form_state->setErrorByName("field content", $error_message);
              }
              if ($has_at) {
                $error_message .= t('The campaign resource Resource Description field cannot contain the @ symbol unless it has spaces on either side.');
                $form_state->setErrorByName("field content", $error_message);
              }
```

2021-08-09 21:33 UTC, bookworm2000 commented on web/modules/custom/sfgov_campaigns/sfgov_campaigns.module
> +              $regex = '/[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})/';
@arlina-espinoza I tried a bunch of email addresses using `.com`, `.net`, `.info`, etc., and this regex finds them all. It does not flag any text strings with spaces on either side of the `@` symbol. I like this for checking but if you think I should change it I will go ahead and do so.

2021-08-09 21:33 UTC, bookworm2000 commented on web/modules/custom/sfgov_campaigns/sfgov_campaigns.module
> +              }
Split this section up so that the error messages are more specific.

2021-08-16 19:52 UTC, arlina-espinoza approved these changes
LGTM, thanks @bookworm2000 :)

2021-08-16 19:52 UTC, arlina-espinoza commented on web/modules/custom/sfgov_campaigns/sfgov_campaigns.module
> +              $regex = '/[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})/';
If works, we can keep it :)

2021-08-16 20:15 UTC, merged