[SG-1469] Handle redirects and banner subtitles for topics
SFDigitalServices/sfgov pull request #973
Opened 2021-08-04 23:54 UTC by bookworm2000

For all news view pages, i.e. `sf.gov/news/topics/4`

2021-08-09 19:12 UTC, arlina-espinoza requested changes
Hi @bookworm2000 , this looks good :) We should just also make it so that node create/edit/deletes cascades to this logic, like for news.

2021-08-09 20:14 UTC, bookworm2000 commented on web/modules/custom/sfgov_utilities/sfgov_utilities.install
> +function sfgov_utilities_update_8705() {
Yes, if we merge PR 957 in first which has update_8704

2021-08-09 21:25 UTC, bookworm2000 commented on web/themes/custom/sfgovpl/includes/views.inc
> +  $nid = !empty($variables['view']->args[0]) ? $variables['view']->args[0]: NULL;
Made this change. Now I need to figure out how to resolve the create/edit/delete logic like in the other ticket (PR 957)

2021-08-10 00:42 UTC, bookworm2000 commented on web/themes/custom/sfgovpl/includes/views.inc
> +  $nid = !empty($variables['view']->args[0]) ? $variables['view']->args[0]: NULL;
Integrated the changes with the other PR so now this is working.

2021-08-16 20:22 UTC, arlina-espinoza submitted a review, later dismissed
LGTM

2021-08-16 22:01 UTC, aekong approved these changes

2021-08-16 22:01 UTC, merged