SG-1448 - translate "Part of" label for transaction
SFDigitalServices/sfgov pull request #974
Opened 2021-08-05 08:37 UTC by aekong

Fixes the translation for the "Part of" label for transactions when coming from a step by step page.

_However_, if a translation in the current language does not exist for that step by step page, the "Part of" label will default to our site's default language (en)

2021-08-09 20:32 UTC, arlina-espinoza requested changes
With the changes introduced in the PR, the "Part of" title gets lost whenever a direct link to that page is shared, because there is no referrer. In addition, if a user access that page through a direct link after a cache clear, it could stay cached that way.
 If the issue is just translating the "part of" strings, Drupal's javscript API could be used for that purpose `Drupal.t()` (see https://www.drupal.org/docs/7/api/localization-api/translating-strings-in-javascript).

2021-08-11 06:32 UTC, aekong commented
Good call.  I've updated the hook to read query params instead.  Thanks!

2021-08-11 18:39 UTC, arlina-espinoza requested changes
@aekong This looks good, but I somehow don't see it working correctly on Pantheon. If you visit https://pr-974-sfgov.pantheonsite.io/zh-hant/decide-if-buying-home-city-help-right-you and then https://pr-974-sfgov.pantheonsite.io/zh-hant/decide-if-buying-home-city-help-right-you?nid=625 it won't show the "part of" section. Maybe we do have to force drupal to use the `url.query_args` cache context?

2021-08-11 18:58 UTC, arlina-espinoza commented on web/themes/custom/sfgovpl/includes/node.inc
> +  $request = \Drupal::request();
@aekong Found how to get the cache to work!: 
```suggestion
  $variables['#cache']['contexts'][] = 'url.query_args';
  $request = \Drupal::request();
```

2021-08-11 19:58 UTC, aekong commented on web/themes/custom/sfgovpl/includes/node.inc
> +  if (empty($fromId)) return;
🤦 thank you!

2021-08-11 19:59 UTC, aekong commented on web/themes/custom/sfgovpl/includes/node.inc
> +  $request = \Drupal::request();
🎉 thank you!

2021-08-16 21:03 UTC, arlina-espinoza approved these changes
LGTM :)

2021-08-16 21:05 UTC, merged