Allow editor to update vaccine sites header description
SFDigitalServices/sfgov pull request #976
Opened 2021-08-06 21:18 UTC by aekong

Exposes the header description text to be user-editable.

Also updates config to match what's currently on production, which is probably unnecessary now that the header text is coming from state

2021-08-06 21:53 UTC, aekong commented on web/themes/custom/sfgovpl/templates/components/vaccine/vaccine-widget--header.twig
> +      {{ header_description | raw }}
@arlina-espinoza now this is no longer coming from the config but from drupal state, do i get translation for free? or do i have to tack on the `|t` filter? or can i even? 😅

2021-08-09 19:29 UTC, arlina-espinoza commented on web/themes/custom/sfgovpl/templates/components/vaccine/vaccine-widget--header.twig
> +      {{ header_description | raw }}
It is still needed :woman_shrugging:

2021-08-09 19:30 UTC, arlina-espinoza requested changes
Just needs the header description to run through `t()`. Everything else looks good.

2021-08-11 17:48 UTC, arlina-espinoza approved these changes
Looks good, thanks @aekong . I just added a suggestion as a comment.

2021-08-11 17:48 UTC, arlina-espinoza commented on web/modules/custom/sfgov_vaccine/src/Services/VaxValues.php
> +    return t($headerDescription);
It would be nice to avoid calling global functions within classes. Instead, make the class use the `StringTranslationTrait`, and call `$this->t()` here.

2021-08-11 19:36 UTC, arlina-espinoza approved these changes
All good to go! :+1:

2021-08-11 19:55 UTC, merged